Add new compiler path
Bambu backend previously looked for clang++16 only in `usr/bin/clang++-16`. The bambu layout changed and clang lives in `usr/compilers/clang-16/bin/clang++-16`. We now therefore probe this new path first, then fallback to the old one if not found.

Symptom: csim and cosim both failed at link with
```
    "Bambu AppImage not detected. Using fallback compiler.
     ... hls_stream.h:59:31: error: cannot be defaulted"
```